# Generated by Django 5.1.2 on 2024-10-24 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_post_rating_delete_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="rating",
        ),
    ]
