# Generated by Django 5.1.2 on 2024-10-24 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_postrating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postrating",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating",
                to="posts.post",
            ),
        ),
    ]
