# Generated by Django 5.1.2 on 2024-10-24 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_alter_postrating_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PostRating",
        ),
    ]
