# Generated by Django 5.1.2 on 2024-10-24 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0009_likes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="likes",
            old_name="post",
            new_name="pos",
        ),
    ]
