# Generated by Django 5.1.2 on 2024-10-24 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0010_rename_post_likes_pos"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Likes",
        ),
    ]
