# Generated by Django 4.2 on 2024-10-25 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0014_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
    ]
