# Generated by Django 4.2 on 2024-10-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0015_remove_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
